// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgozL53WLXLTdwztAunzCvHlHxzWIq8d4',
    appId: '1:1071097425510:web:0131d9fb2d6efcaa5d47a7',
    messagingSenderId: '1071097425510',
    projectId: 'pdf-reader-ce5eb',
    authDomain: 'pdf-reader-ce5eb.firebaseapp.com',
    storageBucket: 'pdf-reader-ce5eb.firebasestorage.app',
    measurementId: 'G-Z78BW6PBNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLyoLzh3gJDHp-i-uIzUvo3nVEtm_48io',
    appId: '1:1071097425510:android:3abbbfbcbfe054c35d47a7',
    messagingSenderId: '1071097425510',
    projectId: 'pdf-reader-ce5eb',
    storageBucket: 'pdf-reader-ce5eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBzxCvM0zWyXFkxyfQKnTN4L-4T-Q8YV0',
    appId: '1:1071097425510:ios:2c5c52acc87bda035d47a7',
    messagingSenderId: '1071097425510',
    projectId: 'pdf-reader-ce5eb',
    storageBucket: 'pdf-reader-ce5eb.firebasestorage.app',
    iosBundleId: 'com.example.pirtukvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBzxCvM0zWyXFkxyfQKnTN4L-4T-Q8YV0',
    appId: '1:1071097425510:ios:2c5c52acc87bda035d47a7',
    messagingSenderId: '1071097425510',
    projectId: 'pdf-reader-ce5eb',
    storageBucket: 'pdf-reader-ce5eb.firebasestorage.app',
    iosBundleId: 'com.example.pirtukvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgozL53WLXLTdwztAunzCvHlHxzWIq8d4',
    appId: '1:1071097425510:web:cd3c8622d461efa05d47a7',
    messagingSenderId: '1071097425510',
    projectId: 'pdf-reader-ce5eb',
    authDomain: 'pdf-reader-ce5eb.firebaseapp.com',
    storageBucket: 'pdf-reader-ce5eb.firebasestorage.app',
    measurementId: 'G-YXJYTX81RF',
  );
}
