// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa9ew-AxEswqpckCYL32oJ_MEeaLLBZwQ',
    appId: '1:397414897523:web:c1af12354c11e0daa7d706',
    messagingSenderId: '397414897523',
    projectId: 'pirtukvan-d0c66',
    authDomain: 'pirtukvan-d0c66.firebaseapp.com',
    storageBucket: 'pirtukvan-d0c66.firebasestorage.app',
    measurementId: 'G-ZF4NVK8Y76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBz1pFNOeSFZIkLY4RBYS4cbFDI_tCNXug',
    appId: '1:397414897523:android:aef5032de5a979f6a7d706',
    messagingSenderId: '397414897523',
    projectId: 'pirtukvan-d0c66',
    storageBucket: 'pirtukvan-d0c66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4X-14hNBeROXwguxRDRCN44_mp5-nx8E',
    appId: '1:397414897523:ios:9f925eb12ce4787ba7d706',
    messagingSenderId: '397414897523',
    projectId: 'pirtukvan-d0c66',
    storageBucket: 'pirtukvan-d0c66.firebasestorage.app',
  iosBundleId: 'ir.jireyar.pirtukvan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4X-14hNBeROXwguxRDRCN44_mp5-nx8E',
    appId: '1:397414897523:ios:9f925eb12ce4787ba7d706',
    messagingSenderId: '397414897523',
    projectId: 'pirtukvan-d0c66',
    storageBucket: 'pirtukvan-d0c66.firebasestorage.app',
  iosBundleId: 'ir.jireyar.pirtukvan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa9ew-AxEswqpckCYL32oJ_MEeaLLBZwQ',
    appId: '1:397414897523:web:0da88dea0223b7d2a7d706',
    messagingSenderId: '397414897523',
    projectId: 'pirtukvan-d0c66',
    authDomain: 'pirtukvan-d0c66.firebaseapp.com',
    storageBucket: 'pirtukvan-d0c66.firebasestorage.app',
    measurementId: 'G-018YW4KDS0',
  );

}